services:
  bolt:
    image: marcoslkz/bolt-ai-prod:arm
    #image: ghcr.io/stackblitz-labs/bolt.diy:stable
    container_name: bolt
    ports:
      - '5173:5173'
    #env_file: ".env.local"
    environment:
      - NODE_ENV=production
      - COMPOSE_PROFILES=production
      # No strictly needed but serving as hints for Coolify
      - PORT=5173
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-1114}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5173/api/health || exit 1"]
    command: sh -c "touch .env.local && pnpm run dockerstart"
    #profiles: - prebuilt
    networks:
      - proxy_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - bolt-diy-data:/usr/src/app/data # Persistent storage for Bolt DIY

volumes:
  bolt-diy-data:    
